name: reviewdog (cfn-lint)

on:
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - '.github/workflows/reviewdog-cfn-lint.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run cfn-lint with reviewdog
        uses: shogo82148/actions-cfn-lint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          filter_mode: nofilter
          fail_on_error: true
          level: warning
          cfn_lint_args: cloudformation.yml
